[project]
name = "obsidian-utilities"
version = "0.0.3"
description = "Fundamental utilities that can be applied to multiple notes that live with the Obsidian application."
authors = ["Jason Boyd <jasonboyd99@gmail.com>"]
maintainers = ["Jason Boyd <jasonboyd99@gmail.com>"]
repository = "https://github.com/itsjaboyd/obsidian-utilities"
keywords = ["obsidian", "notes"]
readme = "README.md"
license = "MIT"

[application]
config = "obsidian-utilities.ini"